name: Android Build

on:
  workflow_dispatch:

env:
  CMAKE_BUILD_PARALLEL_LEVEL: 4
  SPVC_PARAMS: -DSPIRV_CROSS_STATIC=OFF -DSPIRV_CROSS_SHARED=ON -DSPIRV_CROSS_CLI=OFF -DSPIRV_CROSS_ENABLE_TESTS=OFF -DSPIRV_CROSS_SKIP_INSTALL=ON -DSPIRV_CROSS_WERROR=ON -DSPIRV_CROSS_FORCE_PIC=ON

jobs:
  build:
    strategy:
      matrix:
        arch: [ "arm64", "armv7", "x86", "x86_64" ]
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Prepare environment
      run: |
        sudo sed -i 's/^Types: deb$/Types: deb deb-src/' /etc/apt/sources.list.d/ubuntu.sources
        sudo apt update
        sudo apt install build-essential flex bison
    - name: Install toolchain
      run: |
        wget https://github.com/MojoLauncher/gcc-toolchain/releases/download/prebuilt/gcc-13-x86_64-21.tar.xz -O toolchain.tar.xz
        mkdir gcc
        tar xf toolchain.tar.xz -C gcc
        export PATH="$(pwd)/gcc/bin:$PATH"
        mv gcc /opt/gcc-android
    - name: Build
      run: |
        mkdir build && cd build
        cmake .. -DCMAKE_TOOLCHAIN_FILE=../gcc-${{matrix.arch}}.cmake $SPVC_PARAMS
        make -j$(nproc)
        strip libspirv-cross-c-shared.so
    - name: Upload
      uses: actions/upload-artifact@v7
      with:
        name: spvc-${{matrix.arch}}
        path: build/libspirv-cross-c-shared.so
        
        
      
    
